# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Asaad @ IntuitiveHub.Org
email: asaad@asaadshub.com
description: > # this means to ignore newlines until "baseurl:"
  Asaad's technical blog on IntuitiveHub.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://asaad.intuitivehub.org" # the base hostname & protocol for your site
twitter_username: asaadriazmusic
github_username:  anriaz

# Build settings
markdown: kramdown
